### PR TITLE
Moving "dendro" functionality inside it's own folder

### PR DESCRIPTION
**Pull request by dfvankomen**
This PR does exactly what the title says, it seeks to move all of the common and more "internal" Dendro functionality within it's own dendro/ folder.

I've modified the CMake files to properly include it. I've even tried building all of the different solvers that we have (including the CUDA-enabled ones) and everything seems to be good.

I've also added in a Contributing file (which we can edit and modify as needed).

Additionally, there's a new `.clang-format` file, which has some C++ auto-formatting styling that I really like. We could potentially auto-format a good amount of the code to help with visually parsing information. There are some files we may not want to do this with (like the derivatives files that have special formatting to really show the stencils), but the option now exists. I auto-formatted bssnCtx.cpp as an example to see how we like it.

### CODE REVIEW

**Comment by milindasf** [comment]
@dfvankomen Can we directly pull dendro from Dendro-5.01 (https://github.com/paralab/Dendro-5.01) repository and also putting it in a separate folder ?

**Comment by dfvankomen** [comment]
> @dfvankomen Can we directly pull dendro from Dendro-5.01 (https://github.com/paralab/Dendro-5.01) repository and also putting it in a separate folder ?

Do you mean as a submodule? That would be a great idea.

I think we should make a new copy of Dendro-5.01 and name it something like DendroGRLib, or something similar. What do you think?

**Comment by milindasf** [comment]
@dfvankomen My suggestion is to pull dendro stuff from Dendro-5.01 Repo (We need to make sure it is updated). I think we already compile Dendro-5.01 to a library in CMake. Then let Dendro-GR use that library, this way we make sure all the updated Dendro-5.01 stuff is visible to the Dendro-GR repo.

**Comment by dfvankomen** [comment]
@milindasf Ok, I'll make sure Dendro-5.01 is up to date, and then use a Git Submodule in this repository to link them together. I think that'll be a better way to work on it for sure.

**Pull request merged**
